### ISSUE TITLE
Add a hotkey for shop

### ISSUE THREAD

**Issue by Seniru** [Seniru/pewpew#18]
Right now, you can only open the shop by typing out `!shop` which can be tedious at times

A hotkey like `O` or `U` can be really helpful in such cases

**Comment by NathanPang001** [comment]
Hello, could you assign me to this issue?

**Comment by NathanPang001** [comment]
Oh, also wanted to ask if there was a way to test the module without having an account with 1000 cheese. I shouldn't necessarily need to test it, but I want to make sure it works before submitting the pull request.

**Comment by Seniru** [comment]
The gathered cheese to load lua was reduced upto 100 (IIRC). So accounts with that amount of gathered cheese will work. Also I'll check the PR soon. Thanks for the contribution! :heart:
